services:
    api:
        image: beg/api
        environment:
            - NODE_ENV=production
            - DB_FILE_PATH=/app/data/db.sqlite
            - MANDATS_PATH=${MANDATS_PATH-./mandats}
            - JWT_SECRET=${JWT_SECRET-please_change_me}
            - MS_ACCESS_DB_PATH=${MS_ACCESS_DB_PATH-./data/BEGdatas.mdb}
        volumes:
            - ./data:/app/data
            - $MANDATS_PATH:/mandats:ro
            - $MS_ACCESS_DB_PATH:/export-mdb/beg.mdb:ro
            - $FILE_STORAGE:/app/files
        working_dir: /app/apps/api
        command: bun run start
        restart: always
    proxy:
        restart: always
        container_name: "proxy"
        image: beg/proxy
        ports:
            - 8088:443
